# Form implementation generated from reading ui file 'picard-plugin-file-writer/options_file_writer.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_FileWriterOptionsPage(object):
    def setupUi(self, FileWriterOptionsPage):
        FileWriterOptionsPage.setObjectName("FileWriterOptionsPage")
        FileWriterOptionsPage.resize(505, 662)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FileWriterOptionsPage.sizePolicy().hasHeightForWidth())
        FileWriterOptionsPage.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(FileWriterOptionsPage)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.page_title = QtWidgets.QLabel(parent=FileWriterOptionsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.page_title.setFont(font)
        self.page_title.setObjectName("page_title")
        self.verticalLayout_4.addWidget(self.page_title)
        self.format_description = QtWidgets.QLabel(parent=FileWriterOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_description.sizePolicy().hasHeightForWidth())
        self.format_description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.format_description.setFont(font)
        self.format_description.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.format_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.format_description.setWordWrap(False)
        self.format_description.setObjectName("format_description")
        self.verticalLayout_4.addWidget(self.format_description)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.enable_file_writing = QtWidgets.QCheckBox(parent=FileWriterOptionsPage)
        self.enable_file_writing.setChecked(False)
        self.enable_file_writing.setObjectName("enable_file_writing")
        self.verticalLayout_4.addWidget(self.enable_file_writing)
        spacerItem1 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.allowed_files_title = QtWidgets.QLabel(parent=FileWriterOptionsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.allowed_files_title.setFont(font)
        self.allowed_files_title.setObjectName("allowed_files_title")
        self.verticalLayout_4.addWidget(self.allowed_files_title)
        self.allowed_file_paths = QtWidgets.QPlainTextEdit(parent=FileWriterOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.allowed_file_paths.sizePolicy().hasHeightForWidth())
        self.allowed_file_paths.setSizePolicy(sizePolicy)
        self.allowed_file_paths.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        self.allowed_file_paths.setFont(font)
        self.allowed_file_paths.setPlainText("")
        self.allowed_file_paths.setObjectName("allowed_file_paths")
        self.verticalLayout_4.addWidget(self.allowed_file_paths)
        self.vboxlayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(FileWriterOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(FileWriterOptionsPage)

    def retranslateUi(self, FileWriterOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        FileWriterOptionsPage.setWindowTitle(_translate("FileWriterOptionsPage", "window.title"))
        self.page_title.setText(_translate("FileWriterOptionsPage", "page.title"))
        self.format_description.setText(_translate("FileWriterOptionsPage", "page.text"))
        self.enable_file_writing.setText(_translate("FileWriterOptionsPage", "page.cb.enable_file_writing"))
        self.allowed_files_title.setText(_translate("FileWriterOptionsPage", "section.allowed_files.title"))
        self.allowed_file_paths.setPlaceholderText(_translate("FileWriterOptionsPage", "section.allowed_files.placeholder"))
